name: Linting, formatting and testing
on:
  push:
    branches: [main]
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Linting
        run: deno lint
      - name: Formatting
        run: deno fmt --check
      - name: Tests
        run: deno task test:run --reporter=verbose
