name: Linting, formatting and testing
on:
  push:
    branches: [main]
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Lint and format checks
        run: 'deno lint && deno fmt --check'
      - name: Run tests
        run: 'deno task test:run'
